# Generated by Django 5.0 on 2023-12-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baja',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='modificacion',
            name='producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='precio',
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='alta',
        ),
        migrations.DeleteModel(
            name='baja',
        ),
        migrations.DeleteModel(
            name='modificacion',
        ),
    ]
