# Generated by Django 5.0 on 2023-12-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_remove_baja_producto_remove_modificacion_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='texto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
