# Generated by Django 5.0 on 2023-12-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_producto_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='texto',
            new_name='descripcion',
        ),
    ]
